"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](dark_blue)\
$os\
$username\
$hostname\
[](bg:blue fg:dark_blue)\
$directory\
[](bg:cyan fg:blue)\
$git_branch\
$git_status\
[](fg:cyan bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:light_gray)\
$conda\
[](fg:light_gray bg:gray)\
$time\
[ ](fg:gray)\
$cmd_duration\
$line_break\
$character"""

palette = 'nord'

[os]
disabled = false
style = "bg:dark_blue fg:white"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:dark_blue fg:white"
style_root = "bg:dark_blue fg:white"
format = '[ $user]($style)'

[hostname]
ssh_only = false
style = "bg:dark_blue fg:white"
format = '[@$hostname]($style)'

[directory]
style = "bg:blue fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol $branch ](fg:crust bg:cyan)]($style)'

[git_status]
style = "bg:cyan"
format = '[[($all_status$ahead_behind )](fg:crust bg:cyan)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:light_gray"
format = '[[ $symbol( $context) ](fg:white bg:light_gray)]($style)'

[conda]
symbol = "  "
style = "fg:white bg:light_gray"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:gray"
format = '[[  $time ](fg:white bg:gray)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:cyan)'
vimcmd_replace_symbol = '[❮](bold fg:cyan)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = false
format = " in $duration "
style = "bg:gray"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.nord]
crust = "#2e3440"
dark_gray = "#3b4252"
gray = "#434c5e"
light_gray = "#4c566a"
dim_white = "#d8dee9"
white = "#eceff4"
teal = "#8fbcbb"
cyan = "#88c0d0"
blue = "#81a1c1"
dark_blue = "#5e81ac"
red = "#bf616a"
green = "#a3be8c"
